version: '3.8'

services:
  nginx:
    image: nginx:stable
    container_name: "yanlex-wow-guild-front-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs/
      - ../public_html:/var/www/dist/
    networks:
      - wowguild


networks:
  wowguild:
    driver: bridge
    external: true
    name: wowguild